/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        dark_base: "#191724",
        dark_surface: "#1f1d2e",
        dark_overlay: "#26233a",
        dark_muted: "#6e6a86",
        dark_subtle: "#908caa",
        dark_text: "#e0def4",
        dark_love: "#eb6f92",
        dark_gold: "#f6c177",
        dark_rose: "#eb6f92",
        dark_pine: "#31748f",
        dark_foam: "#9ccfd8",
        dark_iris: "#c4a7e7",
        dark_highlight_low: "#21202e",
        dark_highlight_med: "#403d52",
        dark_highlight_high: "#524f67",
        base: "#faf4ed",
        surface: "#fffaf3",
        overlay: "#f2e9e1",
        muted: "#9893a5",
        subtle: "#797593",
        text: "#575279",
        love: "#b4637a",
        gold: "#ea9d34",
        rose: "#d7827e",
        pine: "#286983",
        foam: "#56949f",
        iris: "#907aa9",
        highlight_low: "#f4ede8",
        highlight_med: "#dfdad9",
        highlight_high: "#cecacd",
      },
    },
  },
  plugins: [],
};
